[package]
name = "hello"
version = "0.1.0"
edition = "2021"
default-run = "hello"

[dependencies]

[dev-dependencies]
assert_cmd = "2"

[profile.release]
opt-level = 3
lto = true
# debug = false
strip = true
