[package]
name = "findr"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
regex = "1"
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.83"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
