[package]
name = "uniqr"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
tempfile = "3"
rand = "0.8"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
